version: "3.5"
services:
  akademie:
    image: mindhochschulnetzwerk/${SERVICENAME}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.${SERVICENAME}.entrypoints=websecure
      - traefik.http.routers.${SERVICENAME}.rule=${HOST_RULE}
      - traefik.http.routers.${SERVICENAME}.middlewares=secheader@file
    networks:
      - ${SERVICENAME}
      - traefik
    volumes:
      - "./teilnehmerinfos.md:/var/www/Resources/Private/Templates/Teilnehmerinfos/infos.md"

networks:
  akademie:
    name: ${SERVICENAME}
  traefik:
    name: traefik
    external: true
